export const BNIClient: typeof bniClient;
export const OneGatePayment: typeof oneGatePayment;
export const SnapBI: typeof snapBI;
export const RDN: typeof RDN;
export const RDL: typeof RDL;
export const Rdf: typeof RDF;
export const BNIMove: typeof bniMove;
export const Ecollection: typeof ecollection;
import bniClient from './lib/bniClient.js';
import oneGatePayment from './lib/api/oneGatePayment.js';
import snapBI from './lib/api/snapBI.js';
import RDN from 'lib/api/rdn.js';
import RDL from 'lib/api/rdl.js';
import RDF from './lib/api/rdf.js';
import bniMove from 'lib/api/bniMove.js';
import ecollection from "./lib/api/ecollection.js";
